# Setup
title:            David Stansby
url:              "http://www.davidstansby.com"
baseurl:          ""

author:
  name: 'David Stansby'
  url:  https://twitter.com/davidstansby

sass:
  sass_dir: _sass
